### ISSUE TITLE
Notifications do not seem to work (pushover.net)

### ISSUE THREAD

**Issue by TnTBass** [MPOS/php-mpos#2591] opened 2017-08-30 16:38 UTC
I first setup pushover.net notifications to my phone, and received them for a couple blocks found.  After that, I stopped getting notifications (I have paid for pushover.net, so the trial limitations are not in effect).

My crons send me emails on errors.  I keep getting these same errors.

`PHP Notice:  Only variables should be passed by reference in /var/www/MPOS/include/classes/notification.class.php on line 153`

`PHP Notice:  Only variables should be passed by reference in /var/www/MPOS/include/classes/notification.class.php on line 153`

`PHP Notice:  Only variables should be passed by reference in /var/www/MPOS/include/classes/notification.class.php on line 153`

`PHP Notice:  Only variables should be passed by reference in /var/www/MPOS/include/classes/notification.class.php on line 153`

I am happy to provide more information if you let me know what you need.

**Comment by TheSerapher** [comment] 2017-08-30 17:43
Probably duplicate of https://github.com/MPOS/php-mpos/issues/2586 so closing this since it's the same message. We'll have to wait for the original author to check this out since I won't have time to look at it and fix it myself.

**Closed by TheSerapher** 2017-08-30 17:43 UTC
