### ISSUE TITLE
Blocks found but not credited cron ERROR NEED HELP [using MPOS + NOMP] 

### ISSUE THREAD

**Issue by mario1987** [MPOS/php-mpos#2567] opened 2017-07-08 23:37 UTC
I am finding blocks but shares are not set
![noshares](https://user-images.githubusercontent.com/5938706/27989932-e3a43568-6446-11e7-818b-9df3bb115452.jpg)

here is the screen of the wallet that there are coins found
![wallet](https://user-images.githubusercontent.com/5938706/27989933-ebc44eb8-6446-11e7-8450-194042d0c185.jpg)

the found coins are not accounted:
![no soap account](https://user-images.githubusercontent.com/5938706/27989946-2743c0e0-6447-11e7-8722-845cb7090aa7.jpg)
 

This is the cron error i get
proportional_payout |   | ERROR |   |   | 07/09/2017 10:18:23 | 07/09/2017 10:18:23 | No shares found for block

This is in the log file of prop
2017-07-08 23:18:06 - INFO --> |      Block | ID    |        Username |           Valid |      Invalid |   Percentage |      Payout |    Donation |         Fee |       Bonus |
2017-07-08 23:18:06 - CRIT --> No shares found for this block, aborted: 43587
2017-07-08 23:18:08 - CRIT --> Cronjob is currently disabled due to errors, use -f option to force running cron.

![cron prop](https://user-images.githubusercontent.com/5938706/27989920-a92fa21e-6446-11e7-9e1d-b326af5216b5.jpg)

**Comment by TheSerapher** [comment] 2017-07-09 05:59
There is only a single valid share inserted. And I understood you found blocks, I asked to double check that there are shares inserted too. Also do not mine against the rpc itself and as said before enable MPOS mode in NOMP.

Doesn't seem to be an issue with MPOS. Setup your stratum to properly insert shares. Old blocks will still not be paid out since no shares were ever added so you may have to mark them as paid or truncate the blocks table and start a new wallet to mine in.

**Comment by mario1987** [comment] 2017-07-09 13:31
MPOS is already enabled  look  
![set correctly](https://user-images.githubusercontent.com/5938706/27994301-3e30781a-64bb-11e7-9659-93f77fda85d7.jpg)

I will do another coin  with shares and the result will be the same I will upload the proofs here

**Comment by mario1987** [comment] 2017-07-09 13:34
MPOS was already enabled with this result
![set correctly](https://user-images.githubusercontent.com/5938706/27994329-efc654c8-64bb-11e7-8fac-ce0206f853ba.jpg)
 
I will do another coin and this will show shares but will not credit them I will upload the pic's

**Comment by TheSerapher** [comment] 2017-07-09 14:28
Last one with issues on shares not being assigned to blocks was running the pool in docker containers. He solved it by installing everything on a server.

Something else that came to mind: maybe the coin you are mining is creating more shadow blocks as well. Those not in the main blockchain or mined by miners but still in the wallet. If you run such a coin it's not supported and can only be made to work with (unknown to me) changes to MPOS.

**Comment by mario1987** [comment] 2017-07-09 15:35
I am running it also on a server  I am also able to send the coins to an exchange it tested this out it works fine.

I don't know  if it mined shadow blocks.
I will test it with another coins and see how it goes

**Comment by mario1987** [comment] 2017-07-09 23:59
I have this set up

Type                 = MPOS + NOMP 
MPOS enabled in NOMP = yes
Mining on rpc port = no 
Pool on server     = yes
finding blocks = yes
able to send blocks to exchange and sell them = yes
getting shares  = yes
payment type = prop
type coin = x11
MPOS getting info from wallet = yes
found blocks distributed = no 
NOMP stratum getting work = yes

The coin i use 
![coin mining](https://user-images.githubusercontent.com/5938706/27998548-7a1513bc-6511-11e7-87c5-6347a01d1f60.jpg)

The stratum/NOMP config of the coin  (The mysl login wallet rpc are correct filled in)
![coinconfig1](https://user-images.githubusercontent.com/5938706/27998558-a16b445e-6511-11e7-81cc-f81e1a2d509e.jpg)
![coinconfig2](https://user-images.githubusercontent.com/5938706/27998571-adfa35fe-6511-11e7-97c0-18d019320b1b.jpg)
![coinjson1](https://user-images.githubusercontent.com/5938706/27998574-c73c6758-6511-11e7-8826-52cf34404efb.jpg)
![stratum-works](https://user-images.githubusercontent.com/5938706/27998701-44bdd5d0-6513-11e7-8b66-a3855ae20fcb.jpg)


The config of MPOS (The mysl login wallet rpc are correct filled in)
![mpos-config1](https://user-images.githubusercontent.com/5938706/27998599-14bb190c-6512-11e7-8d30-15d1a69c31b2.png)
![mpos-config2](https://user-images.githubusercontent.com/5938706/27998625-51084d08-6512-11e7-86ec-0ee3521fb5d7.jpg)
![mpos-config3](https://user-images.githubusercontent.com/5938706/27998629-5d150028-6512-11e7-9b98-5275530694cc.jpg)
![mpos-config4](https://user-images.githubusercontent.com/5938706/27998633-69d1c31e-6512-11e7-8667-ab030bfb257b.jpg)
![mpos-config5](https://user-images.githubusercontent.com/5938706/27998636-768c9368-6512-11e7-92ad-552941728375.jpg)
![mpos-config6](https://user-images.githubusercontent.com/5938706/27998643-840df158-6512-11e7-8de2-27bf6893268e.jpg)
![mpos-config7](https://user-images.githubusercontent.com/5938706/27998646-8d2bdd90-6512-11e7-95a8-571ad11a1cd1.jpg)
![mpos-config8](https://user-images.githubusercontent.com/5938706/27998650-94872982-6512-11e7-8a1c-43776532fcdd.jpg)
![mpos-config9](https://user-images.githubusercontent.com/5938706/27998652-9baec526-6512-11e7-981d-30987d3b6bd9.jpg)

The Mpos 
![dashboard](https://user-images.githubusercontent.com/5938706/27998668-db529590-6512-11e7-8053-d96e34a2da1b.jpg)
![shares-proof](https://user-images.githubusercontent.com/5938706/27998660-c0ae1c3c-6512-11e7-861c-6570f98c1aa7.jpg)
![shares-proof confirmation](https://user-images.githubusercontent.com/5938706/27998661-c3f5d966-6512-11e7-80a7-b8600574f2a9.jpg)
![cron prop](https://user-images.githubusercontent.com/5938706/27998671-ea296c10-6512-11e7-9452-6cfb99b60b0a.jpg)
![cronjob-problem](https://user-images.githubusercontent.com/5938706/27998672-ea2b5674-6512-11e7-8f8f-8988a1056cd0.jpg)
![no-transactions](https://user-images.githubusercontent.com/5938706/27998679-f6f2cfd6-6512-11e7-985e-f2ddac7927ab.jpg)
![not-empty](https://user-images.githubusercontent.com/5938706/27998680-f6f58cc6-6512-11e7-96e9-501e7f4e6c04.jpg)
![nothing-on-account](https://user-images.githubusercontent.com/5938706/27998678-f6eafdb0-6512-11e7-891d-348ce1328dbb.jpg)
![shares-proof confirmation](https://user-images.githubusercontent.com/5938706/27998682-fb224ba4-6512-11e7-9fa0-6b17267b2796.jpg)
![wallet-admin](https://user-images.githubusercontent.com/5938706/27998688-101e53e0-6513-11e7-8584-f0007c97dae9.jpg)
![workerproof](https://user-images.githubusercontent.com/5938706/27998690-10738144-6513-11e7-98a3-595ef704d382.jpg)
![wallet](https://user-images.githubusercontent.com/5938706/27998689-106f81ca-6513-11e7-9f17-dfb0060c23ac.jpg)
![block-found-by-miner-proof](https://user-images.githubusercontent.com/5938706/27998696-333a4884-6513-11e7-89a5-a30a95156661.jpg)


Log files Prop etc
![prop-log](https://user-images.githubusercontent.com/5938706/27998693-22097062-6513-11e7-9e44-c7df6eda9dfe.jpg)
![findblock](https://user-images.githubusercontent.com/5938706/27998695-29656cc6-6513-11e7-9f09-718cd1f64a80.jpg)

The miner 
![miner](https://user-images.githubusercontent.com/5938706/27998705-574e58c8-6513-11e7-9252-4be0e549cfaf.jpg)



This is my configuration and results of it

**Comment by TheSerapher** [comment] 2017-07-10 04:35
Logfile and MPOS Indicate that everything worked fine up to a dual locate block for some reason. Since I don't know this coin this may be an issue with the coin itself you tested this time.

Since MPOS is running almost everywhere without any issues you may ask for help for your specific coin in a coin forum (Bitcointalk). I am not following any Crypto coins anymore nor am I planning to add generic support to MPOS for each and every one of those. Most of the times it's just a matter of fixing a few files to make them work, so unless someone watching this project has an idea, try the other forums.

**Comment by knkrth** [comment] 2017-09-30 19:50
Do you find the solution? I'm also having the same problem.

**Comment by chrysophylax69** [comment] 2018-05-18 11:38
I too have recently (almost two weeks ago now) suffered with this issue, and in all those two weeks, I have yet to find a valid fix for this problem.

Our MariaDB/MySQL version is 5.5 - mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1 - under CentOS 7 x64.

Below if the issue ...

2018-05-18 11:26:59 - CRIT -->   No shares found for this block, aborted! Block height: 1257240, Block ID:38504

So far in all my research, there has been no real fix for this issue, and it seems it continuously pops up at one time or another. The pool still runs, but these empty blocks have locked down the pool processes completely.

Marking them as paid has no effect.

Is there a step by step instruction set (for those of us who are not completely versed in MariaDB/MySQL), to show us how to get into the DB and delete these affected blocks completely from the DB? It seems this would be the only way to make sure these empty blocks allow the crons to move forward, and release the pool from the lockdown.

BTW - this has happened to two coins so far in our pool system, and I am certain it would be present in many others in future.

If a fix cannot be found, I would be VERY appreciative of anyone who knows how to delete these block entries to just show me how, so that I can duplicate it in future, until a 'proper' fix could be had.

Thanks,

#crysx

**Comment by TheSerapher** [comment] 2018-05-18 11:57
First off, you can't wipe the DB and then let MPOS run again. Blocks are stored inside your wallet so as long as you don't change the wallet, you can't re-start MPOS (by truncating various tables there). 

Marking them as accounted in the blocks table will make MPOS skip a payment for a block and try to continue.

The reason for this could be .. anything really. MPOS has a detection system which takes the solution from the shares table (a hash) and uses that to find the appropriate block in the block chain. Each share before that solution and after the last blocks found share ID will be used to calculate the round. 
In the past, this was done differently and was prone for errors and using the solution hash has fixed a lot of issues.

In the past there was an issue with Stratum nodes inserting MySQL rows out of order. Which seems to be no big issue at first becomes a big issue on fast block chains. If MySQL inserts Share A, B, C and D where C and D are a proper block solution, MPOS will detect Round 1 with Share C and 3 total shares, Round 2 with share D and 1 total share. Nothing special here.

Placing those shares out of order will result in the error message shown. Again Shares A, B, C and D are our valid shares with C and D being block solutions. If MySQL inserts them in order of A, D, B and C, MPOS will do the following:

* It checks the found blocks table for solved and unaccounted blocks
* It derives the solution to look for in the shares table from the block information
* It detects the block finding share and pays out the round

As Block A was found by Share C and Block B was found by Share D, MPOS will first check Block A and assignes Share C (during block discovery phase, moving from chain to MPOS table). During Payout phase that share will be used to calculate the payouts but note that now the Share D is INSIDE that payout process! MPOS will just use it in that round instead and pay out users. Once Block B comes up in payout, the share used to solve it doesn't exist anymore and no newer shares for this block since last block can be found (since that share is completely gone).

Anyway, that's the technical description of an issue in the past. I would hope that all newer stratum implementations honor the time a share was solved and properly insert them in order so payouts work.

Why is that an issue recently and with some or other coins? No idea ... My first guess would be that during block discovery shares are not found by the solution hash anymore so MPOS has to decide what share to use. Last call is pick a random share within a timeframe of the blocks timestamp and just use that. It's far from perfect but may work for coins with slow block rates. With higher block rates this will not work and result in the errors you describe.

In any case, I have serious doubts it's something that's broken or needs adjustment in MPOS. Two more items on the list should first verify they work as intended: The coin daemon itself (which I would assume is true since they are all Copy & Pasta nowadays anyway) and, more importantly, that the stratum implementation for YAA (yet another algorithm) is done in a way that MPOS can use the share solution as a match for block.

My recommendation? Don't many every coin that gets out there, insist on proper implementations so people don't run into pool operative issues. MPOS isn't supported anymore so new coins will not be added to it nor will I take my time to debug coins that aren't working 100% with it.

This may not be the answer you were looking for, but I have seen this pop up every now and then so I figured I drop more than a few lines and a won't fix :-)

**Comment by TheSerapher** [comment] 2018-05-18 12:05
So I checked the code to see where that error is thrown:

https://github.com/MPOS/php-mpos/blob/master/cronjobs/proportional_payout.php#L69

So it seems that since the last blocks share ID and the recent blocks discovered share ID, shares were deleted including the one that solved the block.

Another idea, which I can't confirm since I don't know the coins that have this issue: They not only solve "normal" blocks discovered by the pools hash rate but maybe additional shadow blocks for some reason. I don't think this is the case but it COULD happen if the block information of such a block matches the one from a pool and would result in a valid solution ...

Since I am curious, lets Open this issue and keep discussing this - I won't be able to fix it but at least it may help people understand what to tweak or how to get around it.

**Comment by TheSerapher** [comment] 2018-05-18 12:10
@chrysophylax69 could you paste some more information in this ticket:

* Relevant log extracts showing find block runs where the blocks that cause issues are discovered
* Relevant DB entry for that block and maybe the previous one so we can see what data MPOS stored for these blocks
* Log extract of the payout phase where that block fails to pay out
* Maybe even the blockchain information on that block and the previous 2, to see how they look in the blockchain

That's just an idea, not sure if we will accomplish anything with that.

As for skipping blocks in the payout phase, it should be enough to run a query like this:

```
UPDATE blocks SET accounted = 1 WHERE height = <block height from log>;
```

Example for the log file you posted:

```
UPDATE blocks SET accounted = 1 WHERE height = 1257240;
```

Running the payout process should now skip this block and not pay it out and continue with the next. If that one also fails, keep updating MySQL until it keeps going.

**Comment by TheSerapher** [comment] 2018-05-18 12:37
I have checked the NOMP code and found that each share solving a block will get the blocks hash as the solution. MPOS can do a matching based on that as well (I think that's even the default, try Hash first and try others if that failed) so if NOMP is detecting blocks correctly and inserts the block hash into the share table for that share, matching it is no issue. And it doesn't seem to be an issue since we do have a block, just not the share for it anymore that picked up that block.

**Comment by chrysophylax69** [comment] 2018-05-18 13:34
Thanks mate ...

I will do what I can in my own capacity, and get the more complex tasks done via our backend developer, who codes the python stratum we use which is more custom than it is 'standard' these days, due to the increase in coins, complexity and updates.

The coins in questions here are SweepStakeCoin (one of our coins) and BernCash (one of the Coin Developers coins external from us).

We do not use NOMP in the backend, and as I have checked, this issue was a NOMP based one. Apologies for that. It is what happens when you read so many of the posts in different issues that you forget where you are actually posting.

MPOS itself is a great Pool System, though deprecated, would make for one hell of a resurgence if it were rewritten from the ground up again. Pity you don't work privately with us to accomplish such a task. Do you commission privately for a contractual fee for private work at all?

In any case, I will give this one more try and see what can be done with this. It is the second time SWEEP has done this, where the first DB was trashed because of it.

I do not have the coding expertise, but will do what needs to be done to get this working. I just run the Company :P 

Would there be a workaround for it in such a case where the blocks ARE actually being minted/pushed too quickly? Any ideas? Anyone?

Lets see how we go with this, and many thanks for the details explanation. Is difficult to find good coders here in Australia, especially ones closeby AND in Crypto.

#crysx

**Comment by TheSerapher** [comment] 2018-05-18 13:47
If you are running a custom python based stratum, check that inserting shares works properly and in order. If everything is in order there and the coins are not generating any weird blocks, this should work. Hence I don't see that MPOS is an issue here, I suspect inserting shares is out of order and causes this for the coins.

And no, I decided to not code anymore. MPOS was my first software project I decided to code to get some experience and see if I like coding. It was fun to write it but I prefer other things during my free time than coding :D

Sadly, I am also not for hire. MPOS was always planned as Open Source, so even if I would go for hire it would be "for the greater good" and MPOS would have to stay open source. I am not a fan of "non-generic" customisations so anything done was always with "keep as generic as possible" in mind. Which worked out rather nicely, even though not perfect.

Now for the minted/pushed to quickly question: There is no issue if everything else in the chain works. I have tested MPOS in the past with test networks and super low diffs causing almost every share to trigger a block. That was actually the reason why I looked at the share detection and fixed it up to work with these kind of coins.

If you do have a developer, run a mining node against a testnet, don't run the payouts though. Run find blocks only. Then look into the shares table and see if shares are out of order for some blocks. And I think with debug logging Findblocks will also log the method used to assign a share to a block. If it's not block hash, you may run into issues :)

**Comment by ultra-pool** [comment] 2018-05-20 05:34
How did you get MPOS to even show up? Ifvdown everything to the T on the guide. Did you have to do any changes or edit of other things?

**Comment by TheSerapher** [comment] 2018-05-20 10:10
If it doesn’t show read error logs of Apache, they tell you what’s wrong. Plus not part of the ticket.

**Comment by TheSerapher** [comment] 2018-05-20 22:33
I am not sure but I think we could close this as something that won’t fix in MPOS. I have the strong suspicion it’s related to a few select coins and it isn’t certain that maybe stratum also played a role here. If you can supply hard evidince that even though everything looks great in the datatbase and MPOS still gets confused with shares then we can look into that. But without any other leads in that direction it is pure guesswork not getting much further.

**Closed by TheSerapher** 2018-05-20 22:33 UTC

**Comment by chrysophylax69** [comment] 2018-05-22 06:06
It seems you are correct mate ...

Since pushing the commend that you posted earlier about committing the block as being paid, the crons pushed through and have since sorted the processes out. It does seem to be only these select coins so far, and the only other issue that we had a while back (which was rectified by a similar method) was the double payout error. Though the fix for that was being done for the fix for this issue which was why it wasn't working.

http://ame-po01.chainworksindustries.com/sweep/index.php?page=dashboard

The CWI-Pool SweepStakeCoin - part of the Pyroxene (theMINE) platform now - seems to be runnign smooth now. I think that if there was a module that was written into the MPOS code to look out for these things and activate the 'mark as paid' solution, then the pool would run a lot more smooth.

I understand that the code is no longer supported by you, and that you are no longer coding, but we would be very happy to take on such a project and continue support (at least in the backend/background side) as long as we had the people to continue working on it. Or at the very least setup a new platfor that works on a similar basis.

We are looking into that side of it currently ;)

Thanks again mate,

#crysx

**Comment by chrysophylax69** [comment] 2018-05-22 14:24
Well - let us know if that is the case, and we will be happy to work with you, or alongside you mate.

#crysx

**Comment by 1ucyph3r** [comment] 2018-10-02 23:16
I can also confirm that MYSQL solution works with Ubuntu Server 16.04. 

In /etc/mysql/mysql.conf.d/mysqld.cnf anywhere under [mysqld] add:

sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

Save file, restart mysql service and everything works.
