### ISSUE TITLE
Transaction Too Large - MPOS Withdrawal Issue

### ISSUE THREAD

**Issue by daygle** [MPOS/php-mpos#2444] opened 2015-06-30 12:05 UTC
Sebastian - I think we really need to look in to the issue I raised some time back about MPOS failing when a transaction is performed that is greater than the coin daemons maximum allowed transaction.

MPOS Error:- ERROR --> E0078: RPC method sendmany did not return 200 OK: Address: XXXXXXXXXXXXXXXX ERROR: RPC call did not return 200: HTTP error: 500 - JSON Response: [-6] Transaction too large

Also refer to past issue #2346 which you closed advising that you didn't have the time for it.

This issue keeps appearing in a number of my pools.

I'm thinking if possible we limit manual and automatic payouts to only pay the maximum payout figure set in the MPOS config file ($config['ap_threshold']['max'] = 250;) - I guess we would need to create another $config['mp_threshold']['max'] = 250;.

If payout is greater that maximum payout only pay maximum payout figure (leaving outstanding funds greater than the maximum payout against users account so that they are able to perform a second payout). This would eliminate the payout cron from halting!

I understand that @xisi was building something but I never got to see it :(

I really hope something can be done.

**Comment by TheSerapher** [comment] 2015-06-30 12:38
Hey @daygle,

Sadly nothing has changed on my situation and I will not be able to set this straight. The change required to make this work is rather significant:

* Transactions are now loaded and booked if they exceed a payout threshold
* All transactions for all users are marked as archived and are paid out
* It is not looked at single transaction to find out if the max threshold could be used instead

This is really a major change and nothing easy to do. It's also changing a core system, payout processing, that has been prone to errors way back when MPOS started. We'd have to change the entire way how coins are sent.

Also, I am not sure this will fix it. Transaction too large is caused by the count of transaction, not the amount of coins submitted. Correct me if I am wrong.

So even though I can see this is an issue on some pools with lots of transactions, I can't fix it. I have to rely on others to pick this up and find a solution for it (or describe proper workarounds).

I will leave this open for visibility :-)

**Comment by xisi** [comment] 2015-06-30 14:32
I'll see if I can mock up a fix for this for testing.

**Comment by TheSerapher** [comment] 2015-06-30 14:35
I am sure @daygle is a willing test rabbit for this :-) Maybe on a not too important pool at first.

**Comment by daygle** [comment] 2015-06-30 19:22
Thanks for your reply.

I do have to correct you 'transaction too large' is caused by the amount of coins submitted - it happened with one of my pools where only one payout was being processed which exceeded the coin daemons maximum allowed coin transfer.

I do see this being a serious issue for all MPOS pool owners and hope some sort of fix can be developed.

**Comment by daygle** [comment] 2015-06-30 19:43
Thanks @xisi for also looking in to this.

The best examples I'm able to provide are:-

With my Zetacoin wallet/MPOS pool I know for a fact any transaction greater than 1000 (whether it be a single withdrawal or multiple withdrawals (sendmany) greater than 1000ZET) will cause the MPOS payout cron to halt all together!

With my Fireflycoin I know any transaction greater than 500000 will cause the same.

**Comment by xisi** [comment] 2015-07-01 10:41
Would be great if we could have some back and forth about it on IRC if it's a possibility @daygle.

**Comment by daygle** [comment] 2015-07-02 07:36
I have been thinking about this issue all day...

@xisi particularly the $config['payout']['txlimit_manual'], is that the maximum number of withdrawals requested by users? So 500 users are allowed to request a withdraw.

Or

Is it the maximum amount of generated coin transactions allowed to be sent in one transaction? So Zetacoin for example when the pool finds a ZET block that equals 1 ZET and is classed as one transaction, so hence when $config['payout']['txlimit_manual'] = 500 the manual withdrawal will fail if a user withdraws more than 500ZET?

**Comment by TheSerapher** [comment] 2015-07-03 13:38
Okay I have made a big thinking error I think! The Payout we are talking about here really is just pushing all coins of a user from the MPOS wallet to their offline wallet. Then add a transaction record for this payout in the amount we paid out. There is no archiving updates involved. So your change @xisi will probably help a lot there.

**Comment by feeleep75** [comment] 2015-07-03 14:33
hi - you guys are reinventing the wheel :)

look at this one: https://github.com/MPOS/php-mpos/commit/1ab2e56ad12bde7c698e8eb1711d6a60d24fc1fb

I use it and it works perfectly. Just do not use sendmany.

**Comment by TheSerapher** [comment] 2015-07-03 14:42
We need send many to work. It's mandatory if you run larger pools to keep payout performance up. We don't half ass solutions here ;-)

Just kidding, but I do think we should implement it properly.

**Comment by feeleep75** [comment] 2015-07-03 14:46
frankly - I was considering sendmany but this probably suits very well to coins like bitcoin, litecoin, etc which has a value and predictable diff. For all these shitcoins I had so many 'too large transactions'  that if I would use sendmany I would need to spend 4hr per day resending coins manually ;)

anyway - I am operating quite big Dash pool and normal sending works just fine - never had a single issue. Maybe sendmany is quicker but you have to keep a balance...

**Comment by daygle** [comment] 2015-07-03 14:46
So all I need to do is copy that payouts.php file in to my current build and it should work?

**Comment by feeleep75** [comment] 2015-07-03 14:47
@daygle - do not just direct copy - analyze current payout script version, copy what is needed only, make sure you test it, etc. This solution is quite dirty and old one, but it works for me ;)

**Comment by daygle** [comment] 2015-07-03 14:48
Finally someone else that understands my pain! Manual transactions suck!

**Comment by feeleep75** [comment] 2015-07-03 14:53
haha - good luck!

**Comment by daygle** [comment] 2015-07-04 10:14
Here are some examples from the coin daemon showing coins have limitations:-

root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 100000
error: {"code":-4,"message":"Transaction too large"}
root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 90000
error: {"code":-4,"message":"Transaction too large"}
root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 80000
6bd09756fbc2d9525a48c101289d741bda455c4a898d3f496d240f8656c66718
root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 80000
a7885fd0343051f3532de7a828bee0707d55912bab9cb68aa8ed2d63d6674d45
root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 85000
error: {"code":-4,"message":"Transaction too large"}
root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 82500   error: {"code":-4,"message":"Transaction too large"}
root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 81000
error: {"code":-4,"message":"Transaction too large"}
root@test:~# fireflycoind sendtoaddress FgLV335dx5RMCj5ScrM5szMgpE2Ysnkvjd 80500
9232e446c04f6554c40290f39ef8112a471c0deb8c4564c4a196dbaec55db86a

**Comment by TheSerapher** [comment] 2015-07-07 09:27
@xisi that change you did looks promising - hopefully @daygle can get some testing done with this on a pool of some kind. Maybe run a test-net pool and send very low max thresholds to enforce multi-payout loops.

**Comment by daygle** [comment] 2015-07-07 10:37
Unfortunately we haven't had much luck the fixes so far, I believe that @xisi needed some more time to examine and develop a fix for this.

Hopefully we get it sorted in the end :+1:

**Comment by TheSerapher** [comment] 2015-07-07 10:42
I am sure he will! And good work so far you two :-)

**Comment by TheSerapher** [comment] 2015-07-15 12:56
Please keep me posted! I'd love to release this in an upgrade once we have it working and well tested on the development branch.

**Comment by daygle** [comment] 2015-07-15 19:41
@xisi any progress with a fix? Let me know if you require help with testing.

**Comment by turnkit** [comment] 2015-09-29 04:12
Please try to fix this.  I use MPOS pools with Defcoin (DFC) and it is typical to have 10,000+ coins for withdrawal.  Having related issues, possibly the same issue.

**Comment by daygle** [comment] 2015-11-01 22:04
@turnkit - This hasn't progressed that much further, happy to be corrected by @xisi... I was hoping for a fix myself.

**Comment by wuhuaping** [comment] 2016-11-14 09:52
怎么用呀 angl77758@163.com

**Comment by TheSerapher** [comment] 2017-07-16 09:00
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.

**Closed by TheSerapher** 2017-07-16 09:00 UTC
