### ISSUE TITLE
Newly mined blocks not confirming

### ISSUE THREAD

**Issue by DenisePalin** [MPOS/php-mpos#2471] opened 2015-11-06 10:53 UTC
**NEWLY MINED BLOCKS ARE NOT CONFIRMING**

Newly mined blocks are not confirming after creating a new wallet with the same coin address. I manually confirmed all old blocks in the database by setting the confirmations column to 120. Cronjobs are working as expected and I've run through the setup guide looking for any descrepencies. Hoping that someone might have had this same experience after creating a new wallet.

There is some history in the page below, I believe that my issue was closed by mistake. It was thought that I was talking about old blocks only.
https://github.com/MPOS/php-mpos/issues/2470

**Comment by TheSerapher** [comment] 2015-11-06 11:15
Use the command line tool of your coin daemon to check if confirmations of your blocks is updating in there. It has to do with the wallet change but I can't say what exactly is causing blocks not to update by the cron. Once you have more information maybe it can be fixed.

Find blocks that did not confirm, fetch their transaction information via coind client and compare to what MPOS should see.

**Comment by TheSerapher** [comment] 2015-11-06 11:19
Also check the cronjob blockupdate log files. Maybe it has an error message when trying to fetch/update information.

**Comment by DenisePalin** [comment] 2015-11-06 18:44
Thanks for the response, it is much appreciated as I'm going a bit mad on this one.

Coin daemon is up-to-date and the blocks mined on the server are updated. The last block mined on the server now has 846 connections, I did check on the command line getting the hash with getblockhash and then using it with getblock.

I've gone through the syslog and cannot find any errors, there nothing there except that the jobs ran. This issue does point to issues with the cron jobs but there is nothing logged. I set all newly mined blocks to confirmed manually. The server is now showing the error...

    Findblocks disabled, new blocks will currently not show up in the frontend

Things just seem to be getting worse. This server was set up by someone else who is now gone, I'm the one who resolved the bloated wallet issue and managed to kill the pool in the process.

**Comment by TheSerapher** [comment] 2015-11-06 19:41
You should check the cron error logs not syslog. These logs should have an error message why they were disabled. This should be the cause for both your disabled crons. You can try forcing them to fix it by it may not help. 

His may sound harsh but the readme states that running pools is not easy. Getting it setup by someone else is not the way to go - it seems though you have learned at least some basics so I am sure you can find the root cause.

Sadly this does not seem to be caused by a bug in MPOS so I can't assist with all my time, but checking the logs (and scrolling back to when it happened the first time, not just the latest errors) could help.

Try the logs again and post the errors but I will close this ticket as its not an issue with MPOS. I shall help as much as I can though :-)

**Closed by TheSerapher** 2015-11-06 19:41 UTC

**Comment by DenisePalin** [comment] 2015-11-07 21:17
Thanks for helping.

Running Ubuntu 13.10 which uses rsyslog, checking the rsyslog conf file it shows that cron is commented out. I have now uncommented it and restarted rsyslog to get cron to log to its own file. Typical Ubuntu advice on cron errors seems to be just to grep CRON on syslog.

I will create a new pool on a new server with the current wallet and coin address, test it and then take the database from the dead pool and restore it to the new server. Bit long winded but I will get full experience of setting up a pool.

**Comment by DenisePalin** [comment] 2015-11-07 22:15
Victory. Running with -f actually updates confirmations and pays out. Just as I was about to give up but saw your mention of trying to force it, I'd seen others talking about the -f flag but only now realise what it applies to.

![Working](http://i.imgur.com/D4Oogh2.png)

OMG, found the MPOS/cronjobs/logs/ directory. I found the error before it started failing.

`CRIT --> Unable to connect to RPC server backend`

The RPC has been restored for a couple of days but the cron jobs continued to fail. Running with the -f flag seems to have flushed out whatever problem was holding up the server. Thanks for your patience, this has at least been a learning experience.

**Comment by TheSerapher** [comment] 2015-11-08 09:05
Good! I figured it be something simple as that. But it's better for you to find the error so you are much better placed now for future issues and how to solve them :-)

Glad things are working again. Have fun with your pool and running MPOS!
