### ISSUE TITLE
error after upgrade ...

### ISSUE THREAD

**Issue by chrysophylax69** [MPOS/php-mpos#2586] opened 2017-08-09 11:02 UTC
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/denarius-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/denarius-mpos/cronjobs/notifications.php on line 61

---

these are the errors that i receive now after i started updating all the mpos installation that were on the previous version ...

instructions were followed where a git pull was made - and the corresponding upgrades script was executed ( /var/www/granite-mpos/upgrade/run_upgrades.php ) ...

all seemed to be running smoothly until a user noticed their account was not shoing up their hashrates and not updating their stats on the pool ...

a few things need to be noted ...

- our granite pool ( as well as - ozc infx bern don ) was running on the older versions without issue for quite some time now ...
- the upgrade was done on all the aforementioned pools - using that same process ... git pull / upgrade script ...
- two newer pools have been created recently ( dnr and sigt ) on the newer code and have been running fine ...
- all pools are using the granite pool db as the shared sso pool ...

since the upgrade - when a full cron force is done ( run-crons.sh -f ) - these errors are displayed no matter which pool we do this for now ...

what could the problem be? ...

please also note - i am NOT a mysql or php expert ... operating systems ( redhat based ) and some coding only - but technically competent to follow experts instructions ( im a network and infrastructure consultant ) ...

xisi used to help me a lot - but he has disappeared and can no longer contact him ...

if there is anything that is missing in what needs to be done - please inform ...

the system is centos 7 x64 - dedicated pool system ...

tanx ...

#crysx

**Comment by TheSerapher** [comment] 2017-08-09 13:31
Might be issue with the new custom push notifications for some reason. I am not able to check out what the exact issue is but maybe someone can take a look. You could try checking out a previous tag and see if that fixes it. The database changes are probably not affecting anything else but maybe try on a test pool or low traffic one.

**Comment by TheSerapher** [comment] 2017-08-09 13:46
Just to confirm, you have created two new pools with the new version accessing the SSO DB as the other pools but it's not showing any issues?

**Comment by chrysophylax69** [comment] 2017-08-09 17:07
tanx sebastian ...

prior to the upgrade ( granite_db is the sso shared db ) - there was no issue - and the two new pools are based on the new code ... so yes prior to the upgrade ... no now the upgrade has been done - and the granite db has got this issue ...

so if i started another pool - with the current git clone - and setup the entire pool with coin daemon and stratum - there shouldnt be any issues ( as there were no issues with dnr and sigt pools ) ... as soon as the upgrade happened with grn pool - ALL the pools have this issue ...

so im stuck as to why ... and the common denominator is the grn pool ...

#crysx

**Comment by chrysophylax69** [comment] 2017-08-09 17:13
i have an idea ...

there are other pools that we have built - but they have been disabled at the moment ...

if i can check to see which pool has been built with the latest code ( 1.0.7 ) - and bring the pool up on its own WITHOUT sso - this pool could be tested and see if it has the symptomatic errors the others have ...

how would i know by looking at the files which pool is the latest code? ...

#crysx

**Comment by TheSerapher** [comment] 2017-08-09 19:11
https://github.com/MPOS/php-mpos/blob/master/include/version.inc.php

This may be a very isolated issue than but give Debugging a shot. There should be something that gives a hint why these warnings suddenly show up and why hashrate don't seem to show at all. Even though hashrate doesn't seem to be anything changed by that code, could be something else entirely. DB Upgrade to 5.7 maybe?

**Comment by chrysophylax69** [comment] 2017-08-10 05:43
[root@pool bin]# /var/www/granite-mpos/cronjobs/run-crons.sh 
Please be aware: This cron is deprecated and will be removed. Please read: https://github.com/MPOS/php-mpos/wiki/Cronjobs#setup
PHP Notice:  Undefined index: count_all in /var/www/granite-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/granite-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/granite-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/granite-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/granite-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/granite-mpos/cronjobs/notifications.php on line 61
You have mail in /var/spool/mail/root

---

thats strange - as this time there were not so many errors ...

this is becoming more perplexing by the minute ... ill have more time to devote to this in a few hours ...

#crysx

**Comment by TheSerapher** [comment] 2017-08-10 07:50
Probably less notifications to be sent. But it also only a notice, not an error. Seems like variables are empty that shouldn't.

**Comment by scorpio18** [comment] 2017-08-11 15:08
I'm using another SSO method on my pool and after i git pull the latest mpos code i got this error 

PHP Notice:  Only variables should be passed by reference in /var/www/pool/include/classes/notification.class.php on line 153

**Comment by TheSerapher** [comment] 2017-08-11 16:45
Not sure if your implementation is doing this then since it's a different error from others.

I pinged @blondak who did the initial PR for this supporting push notifications. He may have overloooked a few edge cases like SSO :-)

**Comment by blondak** [comment] 2017-08-11 17:54
I'm on holidays till Sunday, I'm going to check it on Monday... 

⁣Tento email byl odeslán pomocí mobilního telefonu, omluvte tedy mou stručnost. ​

11. 8. 2017 18:46, 18:46, Sebastian Grewe <notifications@github.com> napsal/a:

**Comment by scorpio18** [comment] 2017-08-27 11:43
any news about this issue ??

**Comment by TnTBass** [comment] 2017-08-30 18:27
Would be interested in knowing as well.  I am not using SSO, but have these issues.
https://github.com/MPOS/php-mpos/issues/2591

**Comment by blondak** [comment] 2017-09-04 12:33
what is version of database showed in index.php?page=admin&action=dashboard ?

**Comment by scorpio18** [comment] 2017-09-04 13:10
This is my version , the latest 
![mpos](https://user-images.githubusercontent.com/7648927/30027813-25b664fa-918b-11e7-8034-7d8338b54245.png)

For SSO i don't use the mpos sso from the config , i just created view on the pool db to the database that has all the accounts and workers

**Comment by blondak** [comment] 2017-09-04 13:16
than you probably need create view for table user_settings https://github.com/MPOS/php-mpos/blob/master/upgrade/definitions/1.0.1_to_1.0.2.inc.php#L13 ?

**Comment by blondak** [comment] 2017-09-04 13:28
scorpio18: can you try https://github.com/blondak/php-mpos/commit/0307e1e62ddab00a934be797a11668b2b6028c89 ?

**Comment by TnTBass** [comment] 2017-09-04 15:41
@blondak 
I have implemented that change on my pool.  I tested it with a simple login notification, and after logging out/back in, I immediately got a notification.

Seems to be fixed for me.  I'll keep an eye on it and see if I get notifications for blocks found/payouts as well, but I am sure they're probably fixed too.

**Comment by scorpio18** [comment] 2017-09-04 15:43
I get the notification but i get this error on each time the cronjob runs 

PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/pool/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/pool/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/pool/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130

**Comment by blondak** [comment] 2017-09-04 18:06
@scorpio18 not related to push notifications, but try this https://github.com/blondak/php-mpos/commit/70ea8f1609467e79e33d8f3cba45356555898b1a

**Comment by blondak** [comment] 2017-09-04 18:21
@scorpio18 - tested notifymyandroid.com with https://github.com/blondak/php-mpos/commit/f6bfc10b900c9f12b115be53408eea1eebf7998c and working for me, check your api key,...

**Comment by scorpio18** [comment] 2017-09-04 18:42
i get the same error 
PHP Notice: Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130
PHP Notice: Undefined index: username in /var/www/pool/cronjobs/notifications.php on line 61

could this be because i use php 7

PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by TnTBass** [comment] 2017-09-04 22:19
@blondak I no longer see errors in my cron job, but I still have not received notifications for blocks found.  It seems the notifications are not being created, as I do not see them in my notification history under the "My Account -> Notifications section."
If I enable login notifications I see those come through pushover, just not any block found notifications.

**Comment by TnTBass** [comment] 2017-09-05 16:23
@blondak It looks like the only time I get push notifications is when I enable email notifications at the same time.  
Multiple blocks have been found during this time, but no notifications have been received, and no notifications have been created in the "My Account -> Notifications" section in MPOS.  This is when I have set only push notifications using pushover.net.
I have disabled notifications and enabled them again only for push notifications, yet that hasn't solved the issue.

I don't think this is intended, I believe a person should be able to select either push or email (or both) for notifications, but it seems as if push notifications only work when email notifications are enabled as well.

**Comment by blondak** [comment] 2017-09-05 16:53
@TnTBass I will check it later tomorrow

**Comment by blondak** [comment] 2017-09-05 18:10
@TnTBass can you try https://github.com/blondak/php-mpos/commit/d687cab6c1ef60d089ccdeedcf26542871505be0 ?

**Comment by TnTBass** [comment] 2017-09-05 21:36
@blondak Implemented, now just waiting for a block.

**Comment by TnTBass** [comment] 2017-09-05 21:46
@blondak 
That looks to have done it.  I do not have email notifications on for a block, and I have received a pushover.net notification.

However, now I see this error:
PHP Warning:  require_once(/var/www/MPOS/cronjobs/../include/classes/notification.class.php): failed to open stream: No such file or directory in /var/www/MPOS/include/autoloader.inc.php on line 70
PHP Fatal error:  require_once(): Failed opening required '/var/www/MPOS/cronjobs/../include/classes/notification.class.php' (include_path='.:/usr/share/php') in /var/www/MPOS/include/autoloader.inc.php on line 70

**Comment by chrysophylax69** [comment] 2017-09-06 08:26
im just reading and catching up ...

my error still exists - but i have NOT implemented anything as yet ... back soon ...

#crysx

**Comment by chrysophylax69** [comment] 2017-09-06 08:33
ok - so does this change to notifications class need to be done for ALL pools - or just the pool that has the sso db in it? ...

#crysx

**Comment by scorpio18** [comment] 2017-09-06 11:16
I applied all the fixes but still i get same errors 

PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/pool/cronjobs/notifications.php on line 61

I receive the notification e-mail but i don't receive any notification on pushover or notifymyandroid i have checked the api key and is the right one

i don't know if this matters but i'm using mariadb not mysql database

**Comment by TheSerapher** [comment] 2017-09-06 12:05
@blondak I don't know if this is related to your change in the notifications or by the customisation done to the pool itself by using an unsupported SSO system. I'd recommend to focus on regular pools first and if @scorpio18 still needs help you could lend him a hand. I don't think we need a generic solution for a custom made implementation here.

**Comment by chrysophylax69** [comment] 2017-09-06 12:39
ive just tried to implement the changes made to the granite pool - which is the sso db that is used ... and the same issue still exists ...

[root@pool classes]# /var/www/granite-mpos/cronjobs/run-crons.sh -f -d grn
Please be aware: This cron is deprecated and will be removed. Please read: https://github.com/MPOS/php-mpos/wiki/Cronjobs#setup
PHP Notice:  Undefined index: count_all in /var/www/granite-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/granite-mpos/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/granite-mpos/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/granite-mpos/cronjobs/notifications.php on line 61

reverting back to the original notifications file ... but only because its doing exactly the same as before ...

we have just recovered from an old issue also on our sweep pool - with the double payout issue ... what a pain that one is ...

anyway - any suggestions as what can be happening here? ...

by the way - i DID setup a new pool ( sweep ) and before i added it to sso ( granite_db ) i run the cronjobs a few times - and the errors did not occur ... so a new 'clean' git clone of the repo is fine ... it seems only when upgrading there is this issue ...

#crysx

**Comment by TheSerapher** [comment] 2017-09-06 17:35
Maybe @blondak can checkout the old version and run the upgrade. Should then show the same errors as you have.

**Comment by TnTBass** [comment] 2017-09-06 18:51
I have only implemented these fixes:
https://github.com/blondak/php-mpos/commit/70ea8f1609467e79e33d8f3cba45356555898b1a
https://github.com/blondak/php-mpos/commit/d687cab6c1ef60d089ccdeedcf26542871505be0

I am getting push notifications now.  However, I still get this error below.

PHP Notice:  Only variables should be passed by reference in /var/www/MPOS/include/classes/usersettings.class.php on line 34

**Comment by blondak** [comment] 2017-09-06 19:10
@TnTBass try this https://github.com/blondak/php-mpos/commit/b144d21cb385fc621c402e509c20514ad4878246

**Comment by TnTBass** [comment] 2017-09-06 20:54
@blondak I've implemented the fix.  I haven't seen the error pop up anymore, but I'll continue to monitor for a while.

**Comment by chrysophylax69** [comment] 2017-09-07 07:39
will this fix the issue above that im having after the upgrade? ...

im confused as to what these 'fixes' are - and seem to be ignored ...

#crysx

**Comment by TheSerapher** [comment] 2017-09-07 07:58
Debugging is in progress, you also have a special case since you are running your own SSO integration but your hints were already helpful. Once @blondak gets a chance I am sure he will get in touch.

**Comment by TnTBass** [comment] 2017-09-09 19:45
@blondak I see these new errors now.

PHP Notice:  Undefined index: count_all in /var/www/MPOS/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/MPOS/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/MPOS/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/MPOS/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/MPOS/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/MPOS/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/MPOS/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/MPOS/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/MPOS/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/MPOS/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/MPOS/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/MPOS/cronjobs/notifications.php on line 61
5

**Comment by blondak** [comment] 2017-09-12 05:25
@TnTBass it should be fixed by https://github.com/blondak/php-mpos/commit/70ea8f1609467e79e33d8f3cba45356555898b1a strange,...

**Comment by TnTBass** [comment] 2017-09-12 14:37
@blondak - I just double checked.  That's implemented.
`    if ($this->checkStmt($stmt) && $stmt->bind_param('iiiii', $interval, $interval, $interval, $interval, $id) && $stmt->execute() && ($result = $stmt->get_result())) {
 `

**Comment by blondak** [comment] 2017-09-13 16:29
@TnTBass try this https://github.com/blondak/php-mpos/commit/4670e553b21d9679305d0af239faea80cc8bb4c4 but it looks like some problem in data,...

**Comment by TnTBass** [comment] 2017-09-13 16:54
@blondak - Implemented. I will monitor.

**Comment by blondak** [comment] 2017-09-13 17:22
@TnTBass it looks, that system generates notification for deleted worker, but patch above should avoid this behaviour.

**Comment by scorpio18** [comment] 2017-09-13 17:32
i have implemented this fix https://github.com/blondak/php-mpos/commit/4670e553b21d9679305d0af239faea80cc8bb4c4  but still i get errors 

PHP Notice:  Undefined index: monitors in /var/www/pool/include/classes/monitoring.class.php on line 31
PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/pool/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/pool/cronjobs/notifications.php on line 61
PHP Notice:  Undefined index: count_all in /var/www/pool/include/classes/worker.class.php on line 130

**Comment by scorpio18** [comment] 2017-09-13 17:35
I even disabled SSO because if i create views to another database , a view can't read the index and i was thinking maybe because of that i get errors but still even if i disable SSO i get the error and no notification on notifymyandroid or pushover

**Comment by blondak** [comment] 2017-09-13 18:04
@scorpio18 do you apply all patches?

* 0307e1e62ddab00a934be797a11668b2b6028c89
* 70ea8f1609467e79e33d8f3cba45356555898b1a
* f6bfc10b900c9f12b115be53408eea1eebf7998c
* d687cab6c1ef60d089ccdeedcf26542871505be0
* b144d21cb385fc621c402e509c20514ad4878246
* 4670e553b21d9679305d0af239faea80cc8bb4c4

?

**Comment by scorpio18** [comment] 2017-09-13 19:05
I have checked again and all the fixes are implemented and still getting erros but there is one exception if i implement this fix https://github.com/MPOS/php-mpos/commit/d687cab6c1ef60d089ccdeedcf26542871505be0   i need to remove it because i want email notification to 

Now i have git clone your development branch and i get db Database version mismatch (Installed: 1.0.2, Current: 1.0.1).

**Comment by blondak** [comment] 2017-09-13 19:21
https://github.com/MPOS/php-mpos/commit/d687cab6c1ef60d089ccdeedcf26542871505be0 is fix to get notifications working without email notification, but it doesnt break email notifications, it was fix because push notifications was depended on email, when email not was disabled push notification doesnt work too

**Comment by blondak** [comment] 2017-09-13 19:27
@scorpio18 ok, i update my develop from parent master, can you pull and test? Thanks

**Comment by scorpio18** [comment] 2017-09-13 19:37
I git pull but i can't set notifymyandroid because i get 

API key |  
-- | --
API Token/Key |  
Your User Key


![notify](https://user-images.githubusercontent.com/7648927/30396990-1151abb4-98d4-11e7-9b89-be5dcbdc1b45.png)

**Comment by blondak** [comment] 2017-09-14 06:00
@scorpio18 ok, it should look little bit diffrent, try ctrl+f5 or check javascript console, because it should display only API key 
![the pool - mining evolved - account](https://user-images.githubusercontent.com/125672/30414222-c126bf04-9922-11e7-83f2-c161bcbc9940.png)

**Comment by scorpio18** [comment] 2017-09-14 10:29
Is fixed the push notifications settings but still i don't get any notification on notifyandroind or pushover , i just receive the mail notification and no erros

**Comment by blondak** [comment] 2017-09-14 14:46
@scorpio18 at least login notification works for pushover.net even for notifymyandroid.com

**Comment by scorpio18** [comment] 2017-09-14 15:03
I tested with login notification but i don't receive any notification on my mobile app

**Comment by blondak** [comment] 2017-09-14 17:21
ufff, that is strange,... try update my settings (blondak@neser.cz:zu12tg63rnx6c7p), or turn on php loging to file and inspect file or, just die in https://github.com/blondak/php-mpos/blob/development/include/classes/push_notification/notifymyandroid.php#L40 and try to dump result from curl_exec

**Comment by TnTBass** [comment] 2017-09-17 02:02
@blondak 
Lately all I have seen is:
PHP Notice:  Undefined index: monitors in /var/www/MPOS/include/classes/monitoring.class.php on line 31

**Comment by blondak** [comment] 2017-09-18 04:31
@TnTBass do you have properly setup monitorig key in index.php?page=admin&action=settings ?

**Comment by TnTBass** [comment] 2017-09-18 18:33
@blondak I do, at least as far as I know.  I see my uptime being gathered and reported.

**Comment by blondak** [comment] 2017-09-18 18:45
@TnTBass strange, I cannot reproduce this warning,...

**Comment by TnTBass** [comment] 2017-09-19 16:33
@blondak I don't know if its causing any issues.  Monitoring seems to work fine.  I just get that error, but only occasionally.

**Comment by Bushstar** [comment] 2017-09-23 14:19
Upgrade MPOS and applied all the updates but still get.

PHP Notice:  Undefined index: count_all in /var/www/MPOS/include/classes/worker.class.php on line 130
PHP Notice:  Undefined index: username in /var/www/MPOS/cronjobs/notifications.php on line 61

To be safe I'm changing worker.class.php on line 130 from:

    if ($row['count_all'] > 0) {

To:

    if (isset($row['count_all']) && $row['count_all'] > 0) {

Also notifications.php on line 61 from:

      $log->logDebug("    " . $aWorker['username'] . " ...");
      if ($aWorker['hashrate'] > 0) {
        if ($notification->setInactive($aNotification['id'])) {
          $log->logDebug(" updated #" . $aNotification['id'] . " for " . $aWorker['username'] . " as inactive");
        } else {
          $log->logError(" failed to update #" . $aNotification['id'] . " for " . $aWorker['username']);
        }
      } else {
        $log->logDebug(" still inactive");
      }

To:

      if (isset($aWorker['username']) && isset($aWorker['hashrate']) ) {
        $log->logDebug("    " . $aWorker['username'] . " ...");
        if ($aWorker['hashrate'] > 0) {
          if ($notification->setInactive($aNotification['id'])) {
            $log->logDebug(" updated #" . $aNotification['id'] . " for " . $aWorker['username'] . " as inactive");
          } else {
            $log->logError(" failed to update #" . $aNotification['id'] . " for " . $aWorker['username']);
          }
        } else {
          $log->logDebug(" still inactive");
        }
      }

No harm in playing safe and checking those array keys exist and are set to something.

**Comment by chrysophylax69** [comment] 2017-10-10 11:11
does this rectify the issue? ...

we are building a new pool server - and currently installing the new pools ... if this issue persists - then its something inherent in the update ...

bushstar = feathercoin? ... if so - has been one of my most fav coins i used to mine and would have lurved to take it on as one of our coins ChainWorks Industries ( offtopic i know - but had to be said ) ... ;) ...

anyway - will build new system and server - and see whether we get this issue in a new installation ... from memory - i dont think there is an issue on new installs - just upgrades from the previous mpos version ...

#crysx

**Comment by Bushstar** [comment] 2017-10-13 15:12
Yep, I'm that same Bushstar. My GitHub account has an email address on it if you ever want to contact me.

**Comment by chrysophylax69** [comment] 2017-10-20 14:19
awesome ...

id like to catchup with you on whether things have been moving with ftc and where ... not on here of course - so ill contact you next week some time ...

tanx ...

to all - the issue that i originally posted still exists but doesnt seem to be too much of a problem in the everyday operations of the pools ...

we are currently migrating the pools to a much needed upgrade - and currently building the servers and pools ... so this will be a new installation which should be a good test to see whether this issue arises or not ... if it doesnt - then the upgrade process is at fault ... but if it does have an issue with a new installation - then its an inherent issue that need to be rectified somehow ...

will let you know ...

#crysx

**Comment by scorpio18** [comment] 2017-10-28 13:22
Hello
The problem with push notification to notifymyandroid is fixed , the problem was from my side LOL i just did not see those push notification settings on my account lol so there was an Email setting and Push setting and you need to enable both of them or just one depends on what you want to choose to receive just a mail or just a push notification to the app phone or both, and about PHP Notice: Undefined index: count_all and PHP Notice: Undefined index: username error  i fixed that too by applying Bushstart fix and it works

**Comment by TheSerapher** [comment] 2017-10-28 14:11
Once we have a PR against development I willl merge and release a new version.

**Comment by TheSerapher** [comment] 2017-10-30 07:10
Thanks @blondak for your efforts on this! I have merged all your fixes into Development. Maybe @scorpio18 you can checkout the MPOS development branch and see if things are OK now. If everything is good I will merge into master and release a new version.

**Comment by chrysophylax69** [comment] 2017-10-31 13:42
Sebastian.

Will it be easy to 'upgrade' the current incarnation of MPOS that is in production when this fix is pushed AND upgraded?

#crysx

**Comment by TheSerapher** [comment] 2017-10-31 14:23
Yes, the only upgrades that need operator intervention are database upgrades supplied by the upgrade script.

Simply pull the changes that’s all.

**Comment by chrysophylax69** [comment] 2017-10-31 14:30
OK. That's great.

Then when this PR is merged into master, all we have to do is update.

We have started building the new CWI-Pool system MPOS component, so we don't want to rip it all out to reinstall the new release.

Much appreciated mate.

#crysx

**Comment by TheSerapher** [comment] 2017-11-02 09:49
Merged the new version 1.0.8 into master, you can upgrade your installs from master now to the latest version. Also creating a tag if you prefer to checkout that. Closing this issue since the underlying problem was solved.

**Closed by TheSerapher** 2017-11-02 09:49 UTC

**Comment by chrysophylax69** [comment] 2017-11-11 06:50
All seems to be fixed. Much appreciated all involved :)

#crysx
