### ISSUE TITLE
unable to send mail to your address

### ISSUE THREAD

**Issue by Controlhosting** [MPOS/php-mpos#2690] opened 2018-03-06 02:13 UTC
i run SSO and am having issues with tokens being global

**Comment by TheSerapher** [comment] 2018-03-06 05:43
Which tokens?

**Comment by Controlhosting** [comment] 2018-03-06 06:11
All of them.  But the most important one is reset passwd

**Comment by TheSerapher** [comment] 2018-03-06 06:13
This is a stock MPOS installation? I am not aware of any issues with SSO .. been around for a while and no reports regarding mail had been sent.

**Comment by Controlhosting** [comment] 2018-03-06 06:14
Yes it is

**Comment by Controlhosting** [comment] 2018-03-06 06:15
Everything else works as it should.

**Comment by TheSerapher** [comment] 2018-03-06 06:19
So the issue is sending out mails itself?

**Comment by Controlhosting** [comment] 2018-03-06 06:25
https://gyazo.com/9020c4c6b6931607402d7ab2daab82f6
mail sends like blockfind. but when it comes to things that need tokens like password reset, account edit, withdrawl ect.  it wont send

**Comment by TheSerapher** [comment] 2018-03-06 06:31
I can’t see anything wrong with that part, it uses the account ID from the shares table and should setup the token using that ID.

Anyone around with SSO that can give it a try? As far as I can tell this should work without problems.

**Comment by Controlhosting** [comment] 2018-03-06 06:33
well that lead me to think that it isn't reading off the global database. that it is still looking for the account id in that pools DB. next question. how would i get it to look in the right DB?

**Comment by TheSerapher** [comment] 2018-03-06 06:41
I think the global DB works since it didn’t bail on getting the users email which is one step before but setting up the token. Did you setup the pool specific database properly? It may just be missing the proper table for tokens.

Have you read the Wiki about SSO? It’s a simple config setup and setting up a shared database across MPOS instances for accounts, workers and news. Each instance still requires the database scheme but accounts, news and workers could be removed (since the shared is used).

I’d think your setup isn’t right.

**Comment by Controlhosting** [comment] 2018-03-06 06:48
I am pretty sure i did it correctly. i am able to sign into each pool with same creds. workers i left to coin specific db. this is an example of how it is in config
https://gyazo.com/f4bd4acd21002e988ae19277268d818d

**Comment by TheSerapher** [comment] 2018-03-06 06:51
And you confirmed all required tables exists in each coin specific database?

**Comment by TheSerapher** [comment] 2018-03-06 06:54
Oh, and your MySQL username and password used for the global shared database is also able to access the non-shared database and all it's tables inside? Try logging in with that user and check what databases and tables that user can see.

**Comment by TheSerapher** [comment] 2018-03-06 07:08
Since when is the pool running SSO? Have these issues been seen before or did they start recently? Is it a newly added new coin to the pool that suddenly shows this behaviour? Is only one coin in your SSO pool affected or every single coin?

Many questions to narrow it down :)

**Comment by Controlhosting** [comment] 2018-03-06 07:10
the user can see global DB

**Comment by Controlhosting** [comment] 2018-03-06 07:11
i have had SSO since dec 27 2017 and had no reported issues to me. until tonight

**Comment by Controlhosting** [comment] 2018-03-06 07:19
it isn't very often i forget my passwords for anything so i never thought to check. figured other mail was going out just fine.

**Comment by TheSerapher** [comment] 2018-03-06 07:23
Hmm .. it's been running for quite some time and no reports that things didn't work. Strange.

I will see if I can get it setup in VirtualBox later today and test it out.

**Comment by Controlhosting** [comment] 2018-03-06 07:25
well someone didn't need to reset a password till tonight (731) users in DB

**Comment by Controlhosting** [comment] 2018-03-06 07:45
thank you for the response. I look forward to your findings.

**Comment by TheSerapher** [comment] 2018-03-06 08:02
Hey @Controlhosting,

I have no idea what's going on your setup but I just cloned from master and setup a simple MPOS instance with one shared database for accounts, news and workers. I Created the first admin account, logged in, logged out and triggered a password reset without issues. This leads me to think there is something different in your setup and not something wrong with MPOS itself. Here the PW reset success:

<img width="539" alt="screen shot 2018-03-06 at 08 57 44" src="https://user-images.githubusercontent.com/2376835/37020644-c57d50a4-211c-11e8-801e-51e88041c967.png">

And the MySQL table in the non-shared instance:

```
mysql> select * from tokens;
+----+------------+------------------------------------------------------------------+------+---------------------+
| id | account_id | token                                                            | type | time                |
+----+------------+------------------------------------------------------------------+------+---------------------+
|  1 |          1 | c8850246863806ede5215223d9a452953aa87fc8d62a68799e4f305fbcf82e90 |    1 | 2018-03-06 08:57:40 |
+----+------------+------------------------------------------------------------------+------+---------------------+
1 row in set (0.00 sec)

mysql>
```

This is an out-of-the box installation on Ubuntu 16.04, no modifications to it. Crated a basic config and only adjusted the Database host information and the shared table for the accounts, news, workers. Everything worked after that.

Closing this as it's not an issue with MPOS but something in your setup. If I have other ideas I let you know, but I'll be honest, it could be anything.

**Closed by TheSerapher** 2018-03-06 08:02 UTC

**Comment by TheSerapher** [comment] 2018-03-06 08:09
Tested the reset procedure with that token, password reset worked and token was removed from the table.

**Comment by Controlhosting** [comment] 2018-03-06 08:10
okay i guess i will dig into my mailserver. again i appreciate you responding so quickly. ill let you know what happens

**Comment by TheSerapher** [comment] 2018-03-08 06:32
That seems to be a work around for not being able to write tokens to a coin local DB. It might be worth putting those into the shared dB as well.

The sending is another issue - something how you setup your mail? Do other mails work?

Again I have tested MPOS locally without issues and mails being sent so it’s something in your setup.
