### ISSUE TITLE
Uptime Robot not wotk

### ISSUE THREAD

**Issue by mraksoll** [MPOS/php-mpos#2565] opened 2017-07-07 18:41 UTC
Uptime Robot not work always 

UptimeRobot API Key not configured.

i do all how on wiki 

create monitor

put in Friendly Name *

ua.stratum[.work]

in host url of pool
in port stratum port

end for ua.www[.work]

but it now work

WTF do for it's start work ?

 on pool i try put 

apikey|ua.www[.work] 
apikey|ua.www
apikey|ua
apikey|ua.www[.work],

how make this work ???????????

**Comment by TheSerapher** [comment] 2017-07-16 08:56
Don't use [.work], use `.work`. `[]` indicate optional variables. Then use the exact name after the monitoring specific API key. You may have to generate the key since they are not automatically generated. And don't use the master API Key.

**Comment by 0xdamm** [comment] 2017-07-18 05:07
Hello, I've been testing the api in every possible way for several days....
And i can not connect the api with mpos.

here correct format:
m77xxx09x2-8a786axx0b65f0axx2x99fa7|**de.stratum.whatever**

on guide example is it:
MONITOR_API_KEY|MONITOR_NAME,MONITOR_API_KEY|MONITOR_NAME,...
what am I doing wrong?

**Comment by TheSerapher** [comment] 2017-07-18 06:27
Is the Cron running? Any error in its logs?

**Comment by 0xdamm** [comment] 2017-07-18 06:33
[IMG]http://i63.tinypic.com/2ihuyas.png[/IMG]

**Comment by 0xdamm** [comment] 2017-07-18 06:34
the pool its new and i dont found any block..
<a href="http://es.tinypic.com?ref=2ihuyas" target="_blank"><img src="http://i63.tinypic.com/2ihuyas.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by 0xdamm** [comment] 2017-07-18 07:03
yes all running..

<a href="http://es.tinypic.com?ref=v8m1c3" target="_blank"><img src="http://i67.tinypic.com/v8m1c3.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by TheSerapher** [comment] 2017-07-18 07:14
Found the issue, UptimeRobot switched to HTTPS only without a redirect, so the hard-coded URL in the code wasn't valid anymore.

Committing a fix to a branch you can test out, it also includes a small Smarty fix for PHP 7. If you run PHP 6 please check your Apache Error log for any errors caused by this change :-)

**Comment by TheSerapher** [comment] 2017-07-18 07:15
Please try with branch `issue-2565-uptimerobot`.

**Comment by 0xdamm** [comment] 2017-07-18 07:22
Working fine 👍

**Comment by TheSerapher** [comment] 2017-07-18 07:31
Merged into development.

**Closed by TheSerapher** 2017-07-18 07:31 UTC

**Comment by TheSerapher** [comment] 2017-07-18 08:49
Merged and released from Dev to Master as MPOS 1.0.6.
