### ISSUE TITLE
Smarty failure stalls crons / payout

### ISSUE THREAD

**Issue by jpcsupplies** [MPOS/php-mpos#2549] opened 2017-03-06 02:50 UTC
According to CHANGELOG.md I am running 1.0.4 June 19 2015 (yes its a bit dated but issues seem recent)  Some issues may already have workarounds so i'll add as much detail as I can. 

Been getting some intermittent payout issues lately - the three main ones are below.   
Here is a summary:

A: after a dirty server shutdown (ie power failure) it leaves the cron token there, and they just see it and refuse to run unless you use the -f option  (this is minor but part of the narrative here)

B: permissions somehow go wrong (possibly due to unclean shutdown or a launch under root has messed up the permissions.

C: when permissions go wrong payout fails, but MPOS /thinks/ it didnt fail.   The only way to confirm (other than all the hate mail that is) is to run:  
/var/www/html/MPOS/scripts/validate_payouts.php > ~/audit
then inspect the audit file and compare to transaction section in the MPOS admin panel - then *cringe*  manually payout all the failures.

Annoyingly payout failures appear to be intermittent.  The suspicon  I have is sendmany is somehow going wrong.  So when more than one payout goes out in a batch, it fails.  But I am no PHP coder.   Example:
This:
```
Subject: Cron <mpos> /var/www/html/MPOS/cronjobs/run-crons.sh

PHP Fatal error:  Uncaught  --> Smarty: unable to write file
+/var/www/html/MPOS/cronjobs/../templates/compile/cron/wrt579e9230316030.52135819 <--
  thrown in /var/www/html/MPOS/include/smarty/libs/sysplugins/smarty_internal_write_file.php on line 44
PHP Fatal error:  Uncaught  --> Smarty: unable to write file
+/var/www/html/MPOS/cronjobs/../templates/compile/cron/wrt579e92309e9ff9.11674726 <--
  thrown in /var/www/html/MPOS/include/smarty/libs/sysplugins/smarty_internal_write_file.php on line 44
```

Results in this (Failure): Note the lack of a TX# (ive put ?? to show) but it says "confirmed"
```
ID 	Account 	Date 	TX Type 	Status 	Payment Address 	TX # 	Block # 	Amount
34618 	UnpaidAngryUser 	2017-02-21 22:15:06 	TXFee 	Confirmed 	M7vex5zf...Ufp9QAx7 	??	n/a 	0.10000000
34617 	UnpaidAngryUser 	2017-02-21 22:15:06 	Debit_AP 	Confirmed 	M7vex5zf...Ufp9QAx7 	??	n/a 	52.82418465
```

But at the same time I am still getting these (success): Note: the existence of a TX# this time
```
ID 	Account 	Date 	TX Type 	Status 	Payment Address 	TX # 	Block # 	Amount
34612 	HappypaidUser 	2017-02-08 22:50:06 	TXFee 	Confirmed 	M8dMkhfy...Sf8XfmRT 	??	n/a 	0.10000000
34611 	HappypaidUser 2017-02-08 22:50:06 	Debit_AP 	Confirmed 	M8dMkhfy...Sf8XfmRT 	14988128...b8d97bfa 	n/a 	274.90000000


```

In my Audit File I see (address obscured for privacy):
```
|        TX-DB-ID | Username        | Address                            |               Amount |     Status | TX-RPC-ID                                                        |
|           34617 | UnpaidAngryUser 	| M7vetcetcetc | 52.82418465000000000 |    MISSING | n/a                                                              |
|           34611 | HappypaidUser | M8detcetcetc | 274.9000000000000000 |      FOUND | 1498812895b3a75b8b5074984f8a1b04dcc3a371b2dd88ec29fb5586b8d97bfa |

```

**Possible Solutions:**
Possible solution for a) 
add a button in the monitoring section to force a single run with -f or create a new troubleshooting section with such a button, or have a timeout (say 24 hours) if the cron doesnt move on run the force option. If it fails a second time, stick a great big red warning somewhere for an admin to see. 

Possible solution for b)  
add an option (possibly in troubleshooting section) that checks if running as root, then checks/fixes permissions and either suggests (or does it itself) terminating and re-launching under the correct mpos user account.

Possible Solution for C) 
1) add a portal to validate_payments within the admin panel. With an option to re-queue a failed payment from there perhaps.  - Or a manual payment option somewhere.  At the very least not flag a failed transaction as completed to stop it removing the users balance from the ledger if they were not actually paid? (thats pure evil!)

2) add an option to switch to between queueing payments using sendtoaddress;  or sendmany (as other users have suggested - but make it an option not one or the other?)

**Comment by TheSerapher** [comment] 2017-03-06 06:09
Some good ideas there. But keep in mind that all layout related actions have intentionally been left out from the front end to reduce the risk of an attack resulting in loss of payments.

C) is already a known issue though I don't remember what the symptoms are. Are do. know it's caused by too many transaction in a single transfer and would also happen with sendtoaddress.

I think the system in place for a) is sufficient. Nobody should just re run cronjobs without first validating why they failed. Adding a timeout or an option on the front end to force a run will just make people skip their proper checks. You could write a script for expected reboots via Init system to disable cronjobs and wait a bit before actually doing a restart. And as for unexpected reboots, better to check why they aborted.

As for file permissions I'll agree. There could be a bettter check in place for those. I am not even sure I added one. Simple fix really but MPOS won't be able to fix permissions if it's owned by root and it has no full file access.

As for manual payouts, if you have confirmed the validity of a users complaint and want to do payouts, a simple way is grep'ing for all lines with MISSING in it and using awk to extract the fields required to do a manual payout. Simple bash script could take this work off your hands.

C) has a PR open that may help but it hasn't been worked on for months. It's also not a trivial change and changes on the payment system have to be done with extra care as you can imagine.

Thanks for your input, maybe someone will pop up to handle your ideas :-)

**Comment by jpcsupplies** [comment] 2017-03-06 22:40
Reason i favor the re-queue payment option is the previous failures will still show as failures even if you manually paid them, potentially you are manually paying them twice for the same coins :/
re-queued presumably they would not show as failure on subsequent audits; so you only catch the legitimate ones.   Mostly I just note the final few failures and assume the earlier ones are resolved.

**Comment by TheSerapher** [comment] 2017-07-16 09:01
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.

**Closed by TheSerapher** 2017-07-16 09:01 UTC
