### ISSUE TITLE
RPC call failed: Could not resolve host

### ISSUE THREAD

**Issue by 6otah** [MPOS/php-mpos#2554] opened 2017-04-09 08:48 UTC
Hi, I'm trying to run uNOMP + MPOS pool. I got my coin daemons (Bitcoin and Litecoin) run on the same machine as MPOS. Username, password and port match in daemon config file and MPOS config. Here's RPC configuration:

```
$config['wallet']['type'] = 'http';
$config['wallet']['host'] = 'localhost:19332';
```
WIth this config I get 'Could not resolve host' error.
`127.0.0.1:19332` doesn't work too.

I tried to run MPOS on another machine. I put `rpcallowip` with proper ip address in coin config file. In MPOS config I used ip and domain name. Still couldn't resolve host.

Bitcoin and Litecoin showed same results.

Litecoin daemon responds to this command correctly:
`curl --user <username>:<password> --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://localhost:19332/`

**Comment by TheSerapher** [comment] 2017-04-09 10:01
Strange problem but not something that I'd see fixable in MPOS. Either your setup has Ann issue with PHP doing any kind of lookups or there is a hidden character in your connection string causing this.

Closing this since it's not a bug in MPOS itself but likely a setup issue on your end.

**Closed by TheSerapher** 2017-04-09 10:01 UTC
