### ISSUE TITLE
[FIX] scroll right

### ISSUE THREAD

**Issue by nrpatten** [MPOS/php-mpos#2454] opened 2015-07-13 13:32 UTC
Fix the scroll right from pushing the user drop down to the right

Add to mpos.css

```css
.navbar-right {
    float: right !important;
    margin-right: 0;
}
```

**Comment by TheSerapher** [comment] 2015-07-13 13:37
Can you show what exactly is fixed with this? Maybe just two screenshots :-)

**Comment by nrpatten** [comment] 2015-07-13 13:48
![right](https://cloud.githubusercontent.com/assets/4833541/8650931/97f150c0-29b9-11e5-9ccd-09c71a75e329.jpg)
![no scroll](https://cloud.githubusercontent.com/assets/4833541/8650933/9c597dc2-29b9-11e5-8f3a-79ddd0bd4f1f.jpg)

**Comment by TheSerapher** [comment] 2015-07-13 13:51
Does that work on all resolutions/devices?

**Comment by nrpatten** [comment] 2015-07-13 13:53
it should it only takes away margin-right: -14px; that is pushing it over

**Comment by nrpatten** [comment] 2015-07-13 13:59
another one align worker pass and so on with worker name

mpos.css Line 584 add > `vertical-align: middle;`
```css
.table > tbody > tr > td {
    padding: 4px;
    vertical-align: middle;
}
```

**Comment by TheSerapher** [comment] 2015-07-13 14:07
That looks like it's going to be a global change. Maybe others may be affected by this change? Maybe we need a new class for the workers specifically and apply that?

If you resize the window, the Worker Name field doesn't fit anymore. It's caused by the account name added to the input box. Just looks funny when you resize it.

**Comment by nrpatten** [comment] 2015-07-13 14:10
yeah i can see that at only 170% will look at that more another time. but the scroll fix should be good to go it dont seem to affect anything else

**Comment by nrpatten** [comment] 2015-07-13 14:24
With width auto; 100% browser size
![namesize](https://cloud.githubusercontent.com/assets/4833541/8651706/e91b907e-29bd-11e5-8734-345012f1b05f.jpg)

same with browsersize at 150%
![150](https://cloud.githubusercontent.com/assets/4833541/8651737/1011d062-29be-11e5-9327-411b0557d299.png)

With width 100% and browsersize at 150%
![untitled](https://cloud.githubusercontent.com/assets/4833541/8651839/a4534062-29be-11e5-86f4-12770d5d8f2a.jpg)


pretty sure this is what he was talking about ?

**Comment by TheSerapher** [comment] 2015-07-13 14:26
Yep exactly. And I don't think there is a fix for that. Unless we can auto-hide the account name box if the resolution is too small.

**Comment by nrpatten** [comment] 2015-07-13 14:28
Hmm i will have a think about how to fix this.

**Comment by nrpatten** [comment] 2015-07-14 04:16
Pretty sure i got it working
Test account @ http://mpos.gitbox.link 
UserName: test@test.com
PassWord: testing1234

**Comment by TheSerapher** [comment] 2015-07-15 12:50
Thanks man! I have pushed your changes to the development tree :-)

**Comment by TheSerapher** [comment] 2015-07-15 12:51
Closing with changes pushed to development. Maybe some people can test it out some more but I have no issues merging this into master for the next release.

**Comment by TheSerapher** [comment] 2015-07-15 14:00
Sorry but I had to revert this. The login box using the same setup as the worker page is now broken. Text moved way up and is unreadable.

**Comment by nrpatten** [comment] 2015-07-15 14:04
Blah ok will take another look into this

**Comment by TheSerapher** [comment] 2015-07-15 14:05
Like I said, maybe just creating a new class and inheriting from the original one should do the trick.

**Comment by nrpatten** [comment] 2015-07-15 14:06
yeah sounds good

**Comment by nrpatten** [comment] 2015-07-16 10:06
Should be good now
http://mpos.gitbox.link/mpos.css
http://mpos.gitbox.link/templates-bootstrap-account-workers-default.tpl.text

Ref #2377 Fix b9ab718

**Comment by TheSerapher** [comment] 2015-07-21 18:56
Haven't forgotten, just haven't found a time to do it yet. :-)

**Comment by nrpatten** [comment] 2015-07-21 22:12
All good no rush

**Comment by TheSerapher** [comment] 2015-08-03 14:35
I am not ignoring this, just haven't had a time to do it :(

**Comment by nrpatten** [comment] 2015-08-03 23:03
:+1:

**Comment by TheSerapher** [comment] 2015-08-04 07:26
Merged! Thanks man :)

**Closed by TheSerapher** 2015-08-04 07:26 UTC
Labels: theme
